pipeline{
    agent any
    stages {
        stage("Build Frontend") {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/PerroWachooo/PrestaBanco']])
                dir("frontend/front_prestaBanco") {
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image") {
            steps {
                dir("frontend/front_prestaBanco") {
                    script {
                        withDockerRegistry(credentialsId: 'docker-credentials') {
                            bat "docker build -t bastianbrito/prestabanco-frontend ."
                            bat "docker push bastianbrito/prestabanco-frontend"
                        }
                    }
                }
            }
        }
    }
}
