server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/PerroWachooo/tingeso_entrega2
          search-paths: config-data

  application:
    name: config-service